export const actions = {
    profile: {
        DATA_FETCHING: "PROFILE_DATA_FETCHING",
        DATA_FETCHED: "PROFILE_DATA_FETCHED",
        AUTHOR_DATA_FETCHED: "AUTHOR_PROFILE_DATA_FETCHED",
        DATA_FETCH_ERROR: "PROFILE_DATA_FETCH_ERROR",
        USER_DATA_EDITED: "PROFILE_USER_DATA_EDITED",
        IMAGE_UPDATED: "PROFILE_IMAGE_UPDATED",
        BLOG_DELETED: "BLOG_DATA_DELETED",
    },

    blog: {
        DATA_FETCHING: "BLOG_DATA_FETCHING",
        DATA_FETCHED: "BLOG_DATA_FETCHED",
        POPULAR_DATA_FETCHED: "POPULAR_BLOG_DATA_FETCHED",
        FAVOURITES_DATA_FETCHED: "FAVOURITES_BLOG_DATA_FETCHED",
        DATA_FETCH_ERROR: "BLOG_DATA_FETCH_ERROR",
        DATA_CREATED: "BLOG_DATA_CREATED",
        DATA_EDITED: "BLOG_DATA_EDITED",
        BLOG_DELETED: "BLOG_DATA_DELETED",
        BLOG_DETAILS: "BLOG_DETAILS",
    },
};
